
package project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import  javax.swing.JOptionPane;

public class login extends javax.swing.JFrame {

   Connection conn =null;
   Statement st =null;
   
    public login() {
        initComponents();
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn=DriverManager.getConnection("jdbc:mysql://localhost/petshop", "root", "");
            st=conn.createStatement();
            JOptionPane.showMessageDialog(null, "Berhasil koneksi");
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Gagal Koneksi Karena"+ ex);
        }
    }
    
    private void Ceklogin(){
        try{
            if(txtnamalog.getText().equals("") || txtkatalog.getText().equals("")){
                JOptionPane.showMessageDialog(rootPane, "Data Tidak Boleh Kosong", "Pesan", JOptionPane.ERROR_MESSAGE);
                txtnamalog.requestFocus();
                hapuslayar();
            }else{
                st=conn.createStatement();
                String sql = ("SELECT * FROM login WHERE namauser='"+txtnamalog.getText()+"'AND katasandi='"+String.valueOf(txtkatalog.getText()+"'"));
            ResultSet rs = st.executeQuery(sql);
            if(rs.next()){
                this.dispose();
                new Home().setVisible(true);
            }else{
                JOptionPane.showMessageDialog(rootPane, "nama dan kata sandi belum akurat", "pesan",  JOptionPane.ERROR_MESSAGE);
            hapuslayar();
            }
            }
        }catch(Exception e){
            e.printStackTrace();   
        }
    }

    private void hapuslayar(){
        txtnamalog.setText("");
        txtkatalog.setText("");
        txtnamalog.setEnabled(true);
        txtkatalog.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelnama = new javax.swing.JLabel();
        labelkatasandi = new javax.swing.JLabel();
        txtnamalog = new javax.swing.JTextField();
        txtkatalog = new javax.swing.JTextField();
        Bmasuk = new javax.swing.JButton();
        Bdaftar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelnama.setText("nama");

        labelkatasandi.setText("kata sandi");

        Bmasuk.setText("Masuk");
        Bmasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BmasukActionPerformed(evt);
            }
        });

        Bdaftar.setText("Daftar");
        Bdaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BdaftarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelnama)
                            .addComponent(labelkatasandi))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnamalog)
                            .addComponent(txtkatalog, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(Bmasuk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(Bdaftar)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelnama)
                    .addComponent(txtnamalog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelkatasandi)
                    .addComponent(txtkatalog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bmasuk)
                    .addComponent(Bdaftar))
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BmasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BmasukActionPerformed
        Ceklogin();
                    
        
    }//GEN-LAST:event_BmasukActionPerformed

    private void BdaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BdaftarActionPerformed
        this.setVisible(false);
        new registrasi().setVisible(true);
    }//GEN-LAST:event_BdaftarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bdaftar;
    private javax.swing.JButton Bmasuk;
    private javax.swing.JLabel labelkatasandi;
    private javax.swing.JLabel labelnama;
    private javax.swing.JTextField txtkatalog;
    private javax.swing.JTextField txtnamalog;
    // End of variables declaration//GEN-END:variables
}
